# configuration for "master" branch
# build in Release mode and deploy to Azure
-
  branches:
    except:
      - 1.0

  configuration: Debug
  before_build:
    - git submodule update --init --recursive
    - nuget restore
  build:
    project: NadekoBot.sln
    verbosity: minimal
# configuration for all branches starting from "dev-"
# build in Debug mode and deploy locally for testing
-
  branches:
    only:
      - 1.0

  configuration: Debug
  build_script:
    - git submodule update --init --recursive
    - ps: dotnet restore --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://api.nuget.org/v3/index.json --disable-parallel discord.net\src\Discord.Net discord.net\src\Discord.Net.Commands
    - dotnet restore .\src\NadekoBot\
    - dotnet build **/project.json

# "fall back" configuration for all other branches
# no "branches" section defined
# do not deploy at all
-
  configuration: Debug
