#configuration for "master" and "dev" branches
-
version: 1.0.{build}
branches:
  except:
  - 1.0
before_build:
- cmd: >-
    git submodule init

    git submodule update --init --recursive

    nuget restore
build:
  verbosity: minimal
 -
  branches:
    only:
	- 1.0
build_script:
- ps: >-
    #cd $Env:BUILD_SOURCESDIRECTORY

    git submodule update --init --recursive

    cd discord.net\src\Discord.Net

    dotnet restore

    dotnet build

    cd ..\Discord.Net.Commands

    dotnet restore

    dotnet build

    cd ..\..\..\src\NadekoBot

    dotnet restore

    dotnet build
