# configuration for "master" branch
# build in Release mode and deploy to Azure
-
  branches:
    except:
      - 1.0

  configuration: Debug
  before_build
    - git submodule update --init --recursive
    - nuget restore
  build:
    verbosity: minimal
# configuration for all branches starting from "dev-"
# build in Debug mode and deploy locally for testing
-
  branches:
    only:
      - 1.0

  configuration: Debug
  deploy:
    provider: Local

# "fall back" configuration for all other branches
# no "branches" section defined
# do not deploy at all
-
  configuration: Debug
